name: Build plugin PHAR

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: NhanAZ/DevTools/.github/workflows/build-plugin.yml@v1.0.0
    with:
      devtools-ref: a74a784b257a2215007d131492319922bf71bd7b
      php-version: '8.1'
      retention-days: 14
    permissions:
      contents: read
