name: Build plugin PHAR

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: NhanAZ/DevTools/.github/workflows/build-plugin.yml@v2.0.0
    with:
      devtools-ref: 37ed21d38b06f8a5778a9d8b201b2362b6a2a5f2
      php-version: '8.1'
      retention-days: 14
    permissions:
      contents: read
