name: Build plugin PHAR

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: NhanAZ/DevTools/.github/workflows/build-plugin.yml@324e08681d7503afef223e4f82cc5d5fdef65dda
    with:
      devtools-ref: 324e08681d7503afef223e4f82cc5d5fdef65dda
      php-version: '8.1'
      retention-days: 14
    permissions:
      contents: read
